// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(_grunt) {
    _grunt.initConfig({
      zyg_link: {
        op:{
          files: {
            'index.html': ['p/**/*.html']
          }
        }
      }
    });
    _grunt.loadNpmTasks('grunt-zyg-link');
    return _grunt.registerTask('default', ['zyg_link']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
